services:
  - type: web
    name: summarizer-backend
    env: java
    plan: starter
    region: oregon
    healthCheckPath: /
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/Summarizer-*.jar
    envVars:
      - key: PORT
        value: 8001
      - key: H2_CONSOLE_ENABLED
        value: false
      - key: SHOW_SQL
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: APP_LOG_LEVEL
        value: INFO
      - key: CORS_ALLOWED_ORIGINS
        value: https://*.render.com,https://*.vercel.app,https://*.netlify.app
      - key: CORS_ALLOWED_METHODS
        value: GET,POST,PUT,DELETE,OPTIONS
      - key: CORS_ALLOWED_HEADERS
        value: "*"
    secrets:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    autoDeploy: true
    branch: main
